[env:black_f407vg]
platform = ststm32
board = black_f407vg
framework = arduino
upload_protocol = dfu
build_flags = 
    -D USE_TINYUSB
    -D USBD_VID=0x0483
    -D USBD_PID=0x5740
    -D USB_MANUFACTURER="\"ChromaDeck\""
    -D USB_PRODUCT="\"ChromaDeck Controller\""
lib_deps = 
    adafruit/Adafruit TinyUSB Library @ ^3.1.0
    fortyseveneffects/MIDI Library @ ^5.0.3
    fastled/FastLED @ ^3.6.0
    bodmer/TFT_eSPI @ ^2.5.31
    paulstoffregen/Encoder @ ^1.4.2