[env:black_f407vg]
platform = ststm32
board = black_f407vg
framework = arduino
upload_protocol = dfu
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D USBD_VID=0x0483
    -D USBD_PID=0x5740
    -D USB_MANUFACTURER="\"ChromaDeck\""
    -D USB_PRODUCT="\"ChromaDeck Controller\""
    -D HAL_PCD_MODULE_ENABLED
libs_deps = 
    arduino-libraries/MIDIUSB @ ^1.0.5
    fastled/FastLED @ ^3.6.0
    bodmer/TFT_eSPI @ ^2.5.31